### ISSUE TITLE
Is guidelines repo a right place to put Lykke Infrastructure problems solutions?

### ISSUE THREAD

**Issue by gmaf** [LykkeCorp/guidelines#19]
Someone in Lykke already solved a common problem and wants to share a solution with the company. 
Any information that can help people from other teams not to spend time, solving the same common problem. (Infrastructure problems specific to Lykke services and environment)

For example:
* Information about a general approach for migration from old services to new ones.
* Information about a general approach for connecting old services with new ones.

Should he create an issue in this repo https://github.com/LykkeCorp/guidelines? 
Or we should create a separate repo?

**Comment by cameronfletcher** [comment]
If it's Lykke specific infrastructure issues then we have a StackOverglow for teams subscription: https://stackoverflow.com/c/lykke/questions

**Comment by JoeStead** [comment]
No, this isn't the place for that. As @cameronfletcher mentioned, we have SO for teams, and potentially other places to document these things (to be discussed internally)
