### ISSUE TITLE
Decide on JSON DateTime representation

### ISSUE THREAD

**Issue by cameronfletcher** [LykkeCorp/guidelines#2]
Food for thought:
https://nbsoftsolutions.com/blog/designing-a-rest-api-unix-time-vs-iso-8601
https://netflix.github.io/genie/docs/3.0.0/rest/
https://stackoverflow.com/questions/10286204/the-right-json-date-format

Discuss.

**Comment by jchannon** [comment]
In my experience and gone through this before, APIs should stick to same in/same out and that should be ISO8601 formats.  Server side in C# this should be deserialized/serialized to `DateTimeOffset`. Following this approach from the start will cause fewer issues

**Comment by cameronfletcher** [comment]
Any objections?  
If not, @jchannon PR?

**Comment by cameronfletcher** [comment]
More info from the wild: https://twitter.com/jamesbender/status/1095361592559054849?s=19

**Comment by jchannon** [comment]
Wait we're not allowed to murder now?
