### ISSUE TITLE
Decide on logging approach

### ISSUE THREAD

**Issue by aurecchia** [LykkeCorp/guidelines#21]
How do we want to approach logging? Is there a certain framework that we should use? How about integration with the deployment environment? (e.g. integration with Azure Application Insights)

**Comment by jchannon** [comment]
I think Serilog is the defacto library now and we have implemented that in Apollo if people want to take a look at it

**Comment by cameronfletcher** [comment]
I think that for a general approch to logging these days we should be considering structured logging.
