### ISSUE TITLE
Decide on testing framework

### ISSUE THREAD

**Issue by JoeStead** [LykkeCorp/guidelines#23]
For both JS projects, and .NET projects, what testing framework should be used?

.NET Candidates:
xUnit
nunit
MSTest

JS Candidates:

**Comment by jchannon** [comment]
xUnit

**Comment by cameronfletcher** [comment]
With [xBehave ](http://xbehave.github.io/) for BDD tests?

**Comment by JoeStead** [comment]
Yes, if BDD style tests are appropriate, xBehave makes sense

**Comment by jchannon** [comment]
I originally had the thought about BDD, Assert.Equal, FluentAssertions but maybe first approach is to use xUnit which they all use underneath, we can look to set a guidelines for what approach we take when using the tests?

**Comment by JoeStead** [comment]
Yeah
