### ISSUE TITLE
Decide on pagination approach

### ISSUE THREAD

**Issue by JoeStead** [LykkeCorp/guidelines#7]
Paging a collection of items should be consistent across all resources, which means, if we get this wrong, it will have serious implications on consumers of the API

**Comment by jchannon** [comment]
```
"index" : 0,
"pageSize" : 20,
"items: [{"name":"john"}]"
"links" :[{"next":"http://foo.com?index=1"},{"last":"http://foo.com?index=100"}
```

I suggest something like the above, links being an optional bonus

**Comment by ozhelenkov** [comment]
@jchannon looks like Atlassian APIs)
Just a note, nothing against it.

**Comment by jchannon** [comment]
It's a common approach :)
